Revert "chore(deps): bump lkaemmerling/laravel-horizon-prometheus-exporter from 1.7.0 to 1.8.3" (#1103)
Reverts wbstack/api#1091

Seems like this triggered errors:
```
Error: Class "LKDevelopment\HorizonPrometheusExporter\Exporter\CurrentProccesesPerQueue" not found
PHP Notice: Error: Class "LKDevelopment\HorizonPrometheusExporter\Exporter\CurrentProccesesPerQueue" not found in /var/www/html/vendor/lkaemmerling/laravel-horizon-prometheus-exporter/src/Repository/ExporterRepository.php:33
```

We're going to try just undoing this update rather than all of the ones
since then.

Bug: T423429